apiVersion: v1
kind: Service
metadata:
  name: muximux
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: muximux
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-media-muximux
