apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-media-nzbget
  name: nzbget
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-media-nzbget
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-media-nzbget
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: quicksync
                operator: In
                values:
                - "true"
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: CH
        image: linuxserver/nzbget
        imagePullPolicy: Always
        name: nzbget
        ports:
        - containerPort: 6789
          name: nzbget
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: nzbget-config
        - mountPath: /downloads
          name: nzbget-downloads
      volumes:
      - hostPath:
          path: /media/newssds/nzbget-config
          type: ""
        name: nzbget-config
      - hostPath:
          path: /media/nzbget/
          type: ""
        name: nzbget-downloads
