apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
  - name: plex-plex
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    workload.user.cattle.io/workloadselector: deployment-media-plex
