apiVersion: v1
kind: Service
metadata:
  name: plex
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: plex
spec:
  ports:
  - name: plex-plex
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    workload.user.cattle.io/workloadselector: deployment-media-plex
