apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  ports:
  - name: radarr-radarr
    port: 7878
    protocol: TCP
    targetPort: 7878
  selector:
    workload.user.cattle.io/workloadselector: deployment-media-radarr
