apiVersion: v1
kind: Service
metadata:
  name: radarr
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: radarr
spec:
  ports:
  - name: radarr-radarr
    port: 7878
    protocol: TCP
    targetPort: 7878
  selector:
    workload.user.cattle.io/workloadselector: deployment-media-radarr
