apiVersion: v1
kind: Service
metadata:
  name: sonarr
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: sonarr
spec:
  ports:
  - name: sonarr-sonarr
    port: 8989
    protocol: TCP
    targetPort: 8989
  selector:
    workload.user.cattle.io/workloadselector: deployment-media-sonarr
